# Generated by Django 3.1.4 on 2020-12-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Дни недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=150, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рейтинг')),
                ('img', models.ImageField(upload_to='profile_pic/', verbose_name='Аватар')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Ставка')),
                ('category', models.ManyToManyField(related_name='category', to='main_app.Category')),
                ('free_time', models.ManyToManyField(related_name='free_time', to='main_app.Days')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
