# Generated by Django 3.1.4 on 2020-12-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
