# Generated by Django 3.1.4 on 2020-12-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_days_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='time',
        ),
    ]
